---
title: "Bayesian Data Analysis in Ecology Using Linear Models with R, BUGS and Stan"
author: "D.Giusti"
date: "06/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(blmeco)

library(sp)
library(gstat)
library(spBayes)
```


## Chapter 13 - Modeling Spatial Data Using GLMM

```{r}
# load data
data("redstart")
str(redstart)

# LM - fit a linear model (with a Gaussian error distribution) of the counts (log-transformation of the response variable) using a linear and a quadratic effect of elevation 
mod <- lm(log(counts + 1) ~ elevation + I(elevation^2), data = redstart)

# check the standard residual plots - the model does not fit the data well (the normality assumption seems to be violated)
plot(mod)

# check the spatial distribution of the residuals
res <- data.frame(resid=resid(mod), x=redstart$x, y=redstart$y)
coordinates(res) <- c("x", "y")
bubble(res, "resid", col=c("blue","orange"), main="Residuals", xlab="Long", ylab="Lat")

# check spatial correlation by using a semivariogram of the standardized residuals
vario.mod <- variogram(resid(mod)~1, res)
plot(vario.mod)

# check anisotropy of the spatial autocorrelation
vario.mod <- variogram(resid(mod)~1, res, alpha=seq(0,360,by=90))
plot(vario.mod)

# GLM - fit a generalized linear model (with a Poisson error distribution)

# GLMM - fit a generalized linear mixed model (with a Poisson error distribution), to explicitly account for spatial autocorrelation
## standardize the covariates to improve the convergence of the MCMC algorithm
redstart$elevation.z <- as.numeric(scale(redstart$elevation))
redstart$elevation.z2 <- redstart$elevation.z^2
## rescale the geographical coordinates to avoid problems with the numerical estimation of psi
redstart$x <- redstart$x/1000
redstart$y <- redstart$y/1000
## fit a simple GLM and use the estimated parameters as starting values for the MCMC algorithm. generate suitable tuning values by computing the Cholesky factorization of the variance-covariance matrix of the GLM
m0 <- glm(counts ~ elevation.z + elevation.z2, data = redstart, family = poisson)
beta.starting <- coefficients(m0)
beta.tuning <- t(chol(vcov(m0)))
## fit the spatial GLM using an exponential covariance function
n.batch <- 1000
batch.length <- 100
n.sample <- n.batch*batch.length
mod <- spGLM(counts ~ elevation.z + elevation.z2, data = redstart, family = "poisson", coords = as.matrix(redstart[,c("x","y")]), starting = list("beta"=beta.starting, "phi"=0.5, "sigma.sq"=1, "W"=0), tuning = list("beta"=beta.tuning, "phi"=0.5, "sigma.sq"=0.1, "W"=0.01), priors = list("beta.Flat", "phi.Unif"=c(0.01, 50), "sigma.sq.IG"=c(2,1)), amcmc = list("n.batch"=n.batch, "batch.length"=batch.length, "accept.rate"=0.43), cov.model = "exponential", verbose = T, n.report = 10)

```

